export default 
{
    products: [
      {
        _id: '1',
        name: 'long dress',
        category: 'dress',
        image: 'https://media.missguided.com/i/missguided/DD921696_01.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock:4,
      },
      {
        _id: '2',
        name: 'short dress',
        category: 'dress',
        image: 'https://images-na.ssl-images-amazon.com/images/I/817SXxTXFXL.__AC_SX342_QL70_ML2_.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock:8,

      },
      {
        _id: '3',
        name: 'Best Pants',
        category: 'Pants',
        image: 'https://i0.wp.com/www.nasary.com/wp-content/uploads/2019/06/20479-8f8d9c.jpeg?fit=800%2C800&ssl=1.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:8,

      },
       {
        _id: '4',
        name: 'skirt women',
        category: 'Pants',
        image: 'https://cdn.shopify.com/s/files/1/0061/8627/0804/products/1_7284c318-a3af-46bc-9582-e5c742bb2289.jpg?v=1580949120.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:8,

      },
     
        {
          _id: '5',
          name: 'Slim Shirt',
          category: 'Shirts',
          image: 'https://ae01.alicdn.com/kf/H407752994fe34527b4eefd5a57ef2f19M/New-Spring-Lady-Black-Solid-red-white-sexy-Slim-Fit-Tee-Women-Highstreet-Casual-Long-Sleeve.jpg',
          price: 60,
          brand: ' Nike',
          rating: 4.5,
          numReviews: 10,
          countInStock:0,

        },
        {
          _id: '6',
          name: 'Fit Shirt',
          category: 'Shirts',
          image: 'https://i.pinimg.com/originals/89/8b/11/898b1161b3ab5ccf73bfd3b19a11677b.jpg',
          price: 50,
          brand: ' Nike',
          rating: 4.2,
          numReviews: 5,
          countInStock:8,

        },
        {
          _id: '7',
          name: 'long dress',
          category: 'dress',
          image: 'https://i.pinimg.com/originals/1c/a5/7f/1ca57f1a9866e0340006d23d07695e9d.jpg',
          price: 60,
          brand: ' Nike',
          rating: 4.5,
          numReviews: 10,
          countInStock:3,
        },
        {
          _id: '8',
          name: 'skirt women',
          category: 'skirt',
          image: 'https://i.pinimg.com/originals/c1/7a/a3/c17aa3354be9dcbc3580b89144b18dde.jpg',
          price: 50,
          brand: ' Nike',
          rating: 4.2,
          numReviews: 5,
          countInStock:6,
  
        },
        {
        _id: '9',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: 'https://media.greatplains.co.uk/ms/gp/j3kal-womens-fu-cinderpink-chunky-cord-mini-skirt.jpg?404=gp/j3kal.jpg&width=1024&height=1537.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock:0,

      },
      {
        _id: '10',
        name: 'long dress',
        category: 'dress',
        image: 'https://media.missguided.com/i/missguided/DD921696_01.jpg',
        price: 60,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock:4,
      },
      {
        _id: '11',
        name: 'short dress',
        category: 'dress',
        image: 'https://images-na.ssl-images-amazon.com/images/I/817SXxTXFXL.__AC_SX342_QL70_ML2_.jpg',
        price: 50,
        brand: ' Nike',
        rating: 4.2,
        numReviews: 5,
        countInStock:8,

      },
      {
        _id: '12',
        name: 'Best Pants',
        category: 'Pants',
        image: 'https://i0.wp.com/www.nasary.com/wp-content/uploads/2019/06/20479-8f8d9c.jpeg?fit=800%2C800&ssl=1.jpg',
        price: 70,
        brand: ' Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock:8,

      },
    ]
  }